apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - port: 80
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
  type: ClusterIP
